// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTW6jQwOgjjTI-oZL9_LcYaVyYUHHZ8lU',
    appId: '1:1006184739013:web:cda70786a3bccbf26a80ac',
    messagingSenderId: '1006184739013',
    projectId: 'pickpointer',
    authDomain: 'pickpointer.firebaseapp.com',
    storageBucket: 'pickpointer.appspot.com',
    measurementId: 'G-T44GXTD4SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkfZl3cd4qrLNhtp8PD0JeZAVw12m28o',
    appId: '1:1006184739013:android:d9a5a0cfd302fef56a80ac',
    messagingSenderId: '1006184739013',
    projectId: 'pickpointer',
    storageBucket: 'pickpointer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1iaA4vVtw7Ra7G5NtzW9eRv_hLaDTbE',
    appId: '1:1006184739013:ios:77f75ba1c16595946a80ac',
    messagingSenderId: '1006184739013',
    projectId: 'pickpointer',
    storageBucket: 'pickpointer.appspot.com',
    androidClientId:
        '1006184739013-279qjiq5fgig8h1bublh3fif1t71621p.apps.googleusercontent.com',
    iosClientId:
        '1006184739013-f9fru1hpjl9j8v5ei94tho8a1d7hmb01.apps.googleusercontent.com',
    iosBundleId: 'com.pickpointer.app',
  );
}
