# on:
#   workflow_run:
#     workflows: ['Deploy to Hosting']
#     types:
#       - completed
on:
  pull_request:
    branches:
      - main
      - master
      - develop
name: "Deploy to App Distribution"
jobs:
  build:
    name: Deploy to App Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.2"

      - run: flutter pub get

      - name: Build Flutter Android APK
        run: flutter build apk

      # - name: Build Flutter iOS # TODO: activate when iOS account is buyed
      #   run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          group: testers
          file: build/app/outputs/apk/release/app-release.apk
