on:
  pull_request:
    branches:
      - main
      - master
      - develop
name: "Test & Build"
jobs:
  build:
    name: Test & Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.2"
      - run: flutter pub get
      - name: Flutter Test
        run: flutter test

      - name: Build Flutter Android
        run: flutter build apk --debug --split-per-abi
      - name: Build Flutter iOS
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Build Flutter Web
        run: |
          flutter build web --release
          cd build/web
          zip -r web-app.zip .
